/*
 * system_task.h
 *
 *  Created on: 20/07/2015
 *      Author: joao.rosa
 */

#include <stdint.h>

#ifndef SYSTEM_TASK_H_
#define SYSTEM_TASK_H_

typedef enum
{
	SAMPLE_RTC,
	CLEAR_ITLK_ALARM,
	PROCESS_DISPLAY_MESSAGE,
	PROCESS_ETHERNET_MESSAGE,
	PROCESS_CAN_MESSAGE,
	PROCESS_RS485_MESSAGE,
	PROCESS_USB2SERIAL_MESSAGE,
	PROCESS_IIB_MESSAGE,
	POWER_TEMP_SAMPLE,
	EEPROM_WRITE_REQUEST_CHECK,
	LED_STS_TURN_ON,
	LED_STS_TURN_OFF,
	LED_ITLK_TURN_ON,
	LED_ITLK_TURN_OFF,
	SOUND_ITLK_TURN_ON,
	SOUND_ITLK_TURN_OFF,
	SAMPLE_BOARD_TEMP,
	RTC_TEST,
	EXIO_TEST,
	ISO_PS_TEST,
	LOOPBACK_TEST,
	ADCP_TEST,
	RS485_TEST,
	FLASH_TEST,
	RAM_TEST,
	TEMP_SENSE_TEST
}eTask;

extern uint8_t TaskCheck(void);

extern uint8_t TaskSetNew(uint8_t TaskNum);

#endif /* SYSTEM_TASK_H_ */
